#!/system/bin/sh
#
# Copy camera firmware to /data/cfw
#

busybox cp /system/vendor/firmware/SlimISP_GK.bin /data/cfw/SlimISP_GK.bin
busybox cp /system/vendor/firmware/SlimISP_ZK.bin /data/cfw/SlimISP_ZK.bin
busybox chown system /data/cfw/*
busybox chgrp media /data/cfw/*
busybox chmod 0775 /data/cfw/*
